# Generated by Django 4.2.1 on 2023-05-18 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('itemID', models.AutoField(db_column='itemID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('order_items_id', models.AutoField(db_column='Order_Items_ID', primary_key=True, serialize=False)),
                ('menu_item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='MenuItems', to='cashier.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(db_column='Order_ID', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(db_column='Creation_date', default=django.utils.timezone.now)),
                ('time', models.TimeField(db_column='Creation_time', default=django.utils.timezone.now)),
                ('cashier_name', models.CharField(max_length=100)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.menuitem')),
            ],
        ),
    ]
