# Generated by Django 4.2.1 on 2023-05-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(related_name='Items', to='cashier.menuitem'),
        ),
    ]
