# Generated by Django 4.2.1 on 2023-05-20 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_remove_order_menu_item_order_items_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='itemphoto',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='photouploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.PositiveIntegerField(db_column='totalprice', default=0.0),
        ),
    ]
